version: '3.8'

services:
    task_3:
        image: node:latest
        working_dir: /json_server
        volumes:
        - ./:/json_server
        ports: 
        - 8000:3000
        command: bash script.sh